### ISSUE TITLE
fail to import vgg

### ISSUE THREAD

**Issue by miaohxDLUT** [ebarsoum/hpgan#3]
First of all, thanks for the repo. I'd like to train it by myself. But there is a bug as follow:
  File "/home/h/hpgan-master/src/braniac/models/__init__.py", line 2, in <module>
    from . import vgg
ImportError: cannot import name 'vgg' from 'braniac.models' 
I think there may miss a file named 'vgg.py' in 'braniac.models'.
Hoping for answering.

**Comment by ebarsoum** [comment]
The vgg part was based on a old code, it isn't used. Please remove it, I will fix it ASAP.

**Comment by ebarsoum** [comment]
Fixed.
